### ISSUE TITLE
Delay on subtitles that have been transcribed?

### ISSUE THREAD

**Issue by Hello-World-Traveler** [McCloudS/subgen#201]
First off, thank you for Subgen!

Is possible to have a delay on subtitle that have been transcribed?

I had to transcribe a few videos into English subtitles, I am having to be a speed reader.
Could an option be added to delay English subs that have been transcribed? post processing? 

Readable 
```
309
00:23:07,430 --> 00:23:11,270
The myth says that he was born like that.
```

Quick flash or speed reading
```
314
00:23:34,830 --> 00:23:34,926
He was born like Rahim.

320
00:23:52,650 --> 00:23:53,580
he said it was a game of the snake.

321
00:23:55,390 --> 00:23:57,810
When he saw a snake, he never said it.

322
00:23:58,440 --> 00:23:59,650
When he saw a snake, he never said it.

336
00:24:43,690 --> 00:24:44,430
I'm afraid.

337
00:24:48,130 --> 00:24:49,490
I'm afraid.
```
```
526
00:39:46,020 --> 00:39:46,430
I'm going to have to shave my head.

527
00:39:48,630 --> 00:39:51,470
How is it? Beautiful?

528
00:39:53,470 --> 00:39:54,310
I'm tired.
```

Non English to English

The timestamps are too close/quick. What could be done about this?

**Comment by McCloudS** [comment]
I'm not seeing any obvious way to do that.  Do the timestamps line up with the actual content being said, it's just being said too quickly?

**Comment by Hello-World-Traveler** [comment]
I am not sure, what is being said isn't English however there is time for the subtitle to say for a few seconds longer.

Could it be the model?

**Comment by McCloudS** [comment]
> I am not sure, what is being said isn't English however there is time for the subtitle to say for a few seconds longer.
> 
> Could it be the model?

It certainly could be, but it's hard to say if you aren't even sure if the subtitles match the contents native language.  Either way, this isn't a problem that can easily be fixed by subgen (or stable-ts).

The subtitles _should_ display the whole time the content is spoken, then disappear when it's done.  I imagine some dense non-english languages could make it seem like subtitles are just flashing on and off over and over.

**Comment by Hello-World-Traveler** [comment]
I think they do fit with what is going on however I have no real way of knowing this for sure.

It makes sense as some language uses less words then we do for the same sentence. 

`Can be:'tiny', 'tiny.en', 'base', 'base.en', 'small', 'small.en', 'medium', 'medium.en', 'large-v1','large-v2', 'large-v3', 'large', 'distil-large-v2', 'distil-large-v3', 'distil-medium.en', 'distil-small.en', 'large-v3-turbo'
`
What model would you recommand? I have been using large-v3 and this takes 3 to 12 minutes.

**Comment by McCloudS** [comment]
The whisper community largely thinks large-v2 is best.  I’m happy with medium speed versus capability for most of my content.

**Comment by Hello-World-Traveler** [comment]
I started using medium until I updated my system. I will give large-v2 a try.

**Comment by Hello-World-Traveler** [comment]
2 minutes and 32 seconds to complete

```
320
00:24:06,080 --> 00:24:07,960
for Rahim's maternal grandmother, Skiya,

321
00:24:08,600 --> 00:24:11,470
the need to care for her
sickly grandchild took priority

322
00:24:12,000 --> 00:24:13,620
when she saw how much he was suffering.

323
00:24:17,560 --> 00:24:17,800
When I first saw Rahim,

324
00:24:18,660 --> 00:24:21,070
I couldn't help but cry.

```
```

528
00:40:58,320 --> 00:41:00,200
an excited Nat was flown to Italy
```
V3
```
392
00:28:28,850 --> 00:28:30,930
then it will be difficult for me.

393
00:28:32,970 --> 00:28:37,890
Because the cure must always be there.
```
V2

```
385
00:28:27,300 --> 00:28:30,320
Treating Rahim is difficult

386
00:28:33,200 --> 00:28:38,040
because the medicine
must always be there.
```
There is no cure. Sticking with V2

I still get the quick flash but not as much

Using large-v2 , completely different results

**Comment by McCloudS** [comment]
Going to close for now, understanding while not ideal results, outside subgen's control.
